title: Kusmas Meteoriks 2019 hack
email: kusmabite@gmail.com
description: Just some hack
baseurl: "/meteoriks" # the subpath of your site, e.g. /blog
url: "http://kusma.xyz" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: kusmabite
github_username:  kusma

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
